version: 1.0.0

services:
  cljblog:
    build:
      dockerfile: Dockerfile
    image: cljblog
    ports:
      - 80:8888
    volumes:
      - app:/app/
    networks:
      - cljblog-nw
    environment:
      CLJBLOG_PORT: 8888
      CLJBLOG_ADMIN_LOGIN: admin
      CLJBLOG_ADMIN_PASSW: admin123

networks:
  cljblog-nw:
    driver: bridge

volumes:
  app:
